server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false

      routes:
        # EVENT SERVICE
        - id: admin-categories-route
          uri: lb://event-service
          predicates:
            - Path=/admin/categories, /admin/categories/**

        - id: public-categories-route
          uri: lb://event-service
          predicates:
            - Path=/categories, /categories/**

        - id: admin-compilations-route
          uri: lb://event-service
          predicates:
            - Path=/admin/compilations, /admin/compilations/**

        - id: public-compilations-route
          uri: lb://event-service
          predicates:
            - Path=/compilations, /compilations/**

        - id: admin-events-route
          uri: lb://event-service
          predicates:
            - Path=/admin/events, /admin/events/**

        - id: public-events-route
          uri: lb://event-service
          predicates:
            - Path=/events, /events/**

        - id: private-events-route
          uri: lb://event-service
          predicates:
            - Path=/users/*/events/**

        # REQUEST SERVICE
        - id: user-requests-route
          uri: lb://request-service
          predicates:
            - Path=/users/*/requests/**

        # USER SERVICE
        - id: admin-users-route
          uri: lb://user-service
          predicates:
            - Path=/admin/users, /admin/users/**

        # RATING SERVICE
        - id: admin-ratings-route
          uri: lb://rating-service
          predicates:
            - Path=/v1/admin/ratings/**

        - id: public-ratings-route
          uri: lb://rating-service
          predicates:
            - Path=/v1/ratings

        - id: private-ratings-route
          uri: lb://rating-service
          predicates:
            - Path=/v1/*/ratings/**

        # STAT SERVICE
        - id: stat-hit-route
          uri: lb://stats-server
          predicates:
            - Path=/hit

        - id: stat-stats-route
          uri: lb://stats-server
          predicates:
            - Path=/stats