server:
  port: 0

grpc:
  client:
    collector:
      address: 'discovery:///collector'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/main
    username: main
    password: main

  jpa:
    hibernate:
      ddl-auto: update

  cloud:
    openfeign:
      httpclient:
        hc5:
          enabled: true

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      failureRateThreshold: 50
      ignoreExceptions:
        - ru.yandex.practicum.core.interaction.handler.exception.ConflictException
        - ru.yandex.practicum.core.interaction.handler.exception.NotFoundException
        - ru.yandex.practicum.core.interaction.handler.exception.BadRequestException