server:
  port: 0

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/main
    username: main
    password: main

  jpa:
    hibernate:
      ddl-auto: update